version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run: dotnet build -c Release
      - run: bash scripts/test.sh --filter "TestCategory=WinDivert"

  test-ubuntu-1604:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo -E bash scripts/install-dotnet.sh
      - run: sudo -E bash scripts/install-libpcap.sh
      - run: sudo -E bash scripts/test.sh
      - store_test_results:
          path: Test/TestResults

  test-ubuntu-2004:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo -E bash scripts/install-dotnet.sh
      - run: sudo -E bash scripts/install-libpcap.sh
      - run: sudo -E bash scripts/test.sh --filter TestCategory!=SendPacket
      - store_test_results:
          path: Test/TestResults

workflows:
  version: 2
  build:
    jobs:
      - test-windows
      - test-ubuntu-1604
      - test-ubuntu-2004
